import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def run_paired_permutation_test(df_path_or_obj, target_metric, roi, timepoint, state, n_permutations=10000):
    """
    Runs an exact paired permutation test (sign-flipping) between StON and StOFF 
    using the subject-level DataFrame output from the FOOOF/Specparam pipeline.
    
    Parameters:
    -----------
    df_path_or_obj : str, Path, or pd.DataFrame
        The dataframe or path to the CSV generated by the specparam pipeline.
    target_metric : str
        The column name of the metric to test (e.g., 'Adj_14_35_Hz', 'Raw_7_13_Hz').
    roi : str
        The ROI to filter by (e.g., 'Left_Motor').
    timepoint : str
        The timepoint to filter by (e.g., 'rest_pre').
    state : str
        The eye state to filter by (e.g., 'EOpen').
    n_permutations : int
        Number of permutations to run to build the null distribution.
    """
    # 1. Load data
    if isinstance(df_path_or_obj, pd.DataFrame):
        df = df_path_or_obj
    else:
        df = pd.read_csv(df_path_or_obj)
        
    # 2. Filter the dataframe for the specific condition
    mask = (df['ROI'] == roi) & (df['Timepoint'] == timepoint) & (df['Eye_State'] == state)
    subset = df[mask]
    
    if subset.empty:
        raise ValueError(f"No data found for ROI={roi}, Timepoint={timepoint}, State={state}")

    # 3. Pivot the data to align StON and StOFF for each subject
    # This ensures we are subtracting the correct values within the same subject
    pivot_df = subset.pivot(index='Subject', columns='Stim_Condition', values=target_metric).dropna()
    
    if len(pivot_df) < 2:
        raise ValueError("Not enough paired subject data (both StON and StOFF) to run a permutation test.")
        
    on_values = pivot_df['StON'].values
    off_values = pivot_df['StOFF'].values
    
    # 4. Calculate the observed real difference (Mean of ON - Mean of OFF)
    differences = on_values - off_values
    observed_diff_mean = np.mean(differences)
    n_subjects = len(differences)
    
    # 5. Permutation Testing (Sign-Flipping)
    # Under the null hypothesis, StON and StOFF are interchangeable within a subject.
    print(f"Running {n_permutations} permutations for {n_subjects} subjects...")
    permuted_diff_means = np.zeros(n_permutations)
    
    # Pre-generate random signs to speed up the loop
    # Shape: (n_permutations, n_subjects)
    random_signs = np.random.choice([1, -1], size=(n_permutations, n_subjects))
    
    for i in range(n_permutations):
        # Flip the signs of the differences randomly and calculate the new mean
        permuted_diff = differences * random_signs[i]
        permuted_diff_means[i] = np.mean(permuted_diff)
        
    # 6. Calculate the p-value (Two-tailed)
    extreme_count = np.sum(np.abs(permuted_diff_means) >= np.abs(observed_diff_mean))
    p_value = extreme_count / n_permutations
    
    # 7. Print Results
    print("\n" + "="*50)
    print(" PERMUTATION TEST RESULTS")
    print("="*50)
    print(f"ROI:          {roi}")
    print(f"Timepoint:    {timepoint}")
    print(f"Eye State:    {state}")
    print(f"Metric:       {target_metric}")
    print("-" * 50)
    print(f"N Subjects:   {n_subjects}")
    print(f"Mean StON:    {np.mean(on_values):.5f}")
    print(f"Mean StOFF:   {np.mean(off_values):.5f}")
    print(f"Obs Diff:     {observed_diff_mean:.5f} (StON - StOFF)")
    print("-" * 50)
    print(f"p-value:      {p_value:.5f}")
    print("="*50 + "\n")
    
    # 8. Plot the Null Distribution
    plt.figure(figsize=(9, 5))
    plt.hist(permuted_diff_means, bins=50, color='lightsteelblue', edgecolor='black', alpha=0.7)
    
    # Plot observed difference line
    plt.axvline(observed_diff_mean, color='red', linestyle='dashed', linewidth=2.5, 
                label=f'Observed Diff\n(p = {p_value:.5f})')
    
    # Plot the opposite tail for visualization of the two-tailed test
    plt.axvline(-observed_diff_mean, color='red', linestyle='dotted', linewidth=1.5, alpha=0.6)
    
    plt.title(f'Permutation Null Distribution\n{roi} | {timepoint} | {state} | {target_metric}')
    plt.xlabel('Mean Difference (StON - StOFF)')
    plt.ylabel('Frequency')
    plt.legend()
    plt.tight_layout()
    plt.show()
    
    return p_value, observed_diff_mean, permuted_diff_means

# =====================================================================
# EXAMPLE USAGE
# =====================================================================
if __name__ == "__main__":
    # You can pass either the DataFrame object directly from your Canvas function:
    # df_results = analyse_group_rest_specparam(master_data_dict, save_dir)
    # run_paired_permutation_test(df_results, ...)
    
    # OR you can pass the path to the saved CSV file:
    csv_file_path = ""
    
    try:
        # Example: Testing the Aperiodic-Adjusted Beta band in Left Motor during rest_pre with Eyes Open
        p_val, obs, null_dist = run_paired_permutation_test(
            df_path_or_obj=csv_file_path,
            target_metric='Adj_14_35_Hz',
            roi='Left_Motor',
            timepoint='rest_pre',
            state='EOpen',
            n_permutations=10000
        )
    except FileNotFoundError:
        print(f"Please ensure '{csv_file_path}' is available or pass the DataFrame directly.")
